name: Publish package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish to PyPI
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5

    - name: Build
      run: >
        pip install -r requirements/build.txt
        && python -m build

    - name: Upload binaries to release
      run: >
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
