name: Publish package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish to PyPI
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3

    - name: Build
      run: >
        pip install build==1.0.3
        && python -m build

    - name: Upload binaries to release
      run: >
        pip install twine==4.0.2
        && python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
