name: Publish package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish to PyPI
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5

    - name: Build
      run: >
        pip install -r requirements/build.txt
        && python -m build

    - name: Upload binaries to release
      uses: pypa/gh-action-pypi-publish@release/v1
